#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1526426908                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : cn                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

# 苹果商店地址
appstore_link                             : https://apps.apple.com/cn/app/id1526426908                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
# 安卓apk包地址
playstore_link                            : https://aheadedu.oss-cn-shenzhen.aliyuncs.com/app/aheadOa-release-2022-2-21.apk                                          # Enter Google Play Store URL.
presskit_download_link                    : https://www.jxuspt.com/                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.svg                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : 校务通 A6                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : 校务通 A6 - 基于区块链的智慧校园平台

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : AHEAD 智慧校园管理平台
your_link                                 : #https://www.jxuspt.com/     
your_copyright                            : 先锋软件股份有限公司  
your_link_copyright                       : #           
your_city                                 : #Copenhagen                                
email_address                             : #emil.baehr@gmail.com
facebook_username                         :                                           
instagram_username                        : #ebaehr
twitter_username                          : #ebaehr
github_username                           : #emilbaehr
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
# fontawesome_icon_name : https://fa5.dashgame.com/#/%E5%9B%BE%E6%A0%87
features                                  :

  - title                                 : 学校新闻资讯
    description                           : 及时更新学校及更分院新闻资讯，聚焦校园媒体图文、视频信息，第一时间了解校园动态。
    fontawesome_icon_name                 : hashtag
    
  - title                                 : 移动版OA系统
    description                           : 随时随地查看、收发通知、信件，任务等信息，查看个部门、分院工作简报，了解校园师生情况。
    fontawesome_icon_name                 : envelope-open-text

  - title                                 : 党建工作
    description                           : 提供党建动态、党建学习、党内法规、党员查询、党费线上支付服务及入党申请流程管理等。
    fontawesome_icon_name                 : sync

  - title                                 : 教务管理
    description                           : 面向教师职工提供对班级情况的查询、管理、分析统计，学生成绩查询、图书馆等相关服务。
    fontawesome_icon_name                 : users

  
  - title                                 : 校园服务
    description                           : 提供校园内报修查询、维修处理、统计、分析；学生电费管理、投诉管理、用餐管理、门锁管理等。
    fontawesome_icon_name                 : user-graduate

  - title                                 : 财务管理
    description                           : 查看学校各分院学生欠费缴费情况，分院、班级、个人各级收费情况。
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : 人事考勤
    description                           : 考勤管理，请假申请、审批及查询，人员信息修改、查询全校、各分院员工数据分析等。
    fontawesome_icon_name                 : calendar-check

  - title                                 : 招生管理
    description                           : 接入招生管理系统中如招生数据中心，新生报道详细情况等。
    fontawesome_icon_name                 : info-circle

  - title                                 : 更多功能服务
    description                           : 全方位的聚焦校园服务线上业务，完善电子信息化功能和提升业务效率。
    fontawesome_icon_name                 : play-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
# 参考文档： https://jekyllrb.com/docs/deployment/third-party/
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
